# Имя воркфлоу
name: Data Pipeline

on:
  # Запуск по расписанию каждый час
  schedule:
    - cron: '0 * * * *'
  # Позволяет запускать вручную из интерфейса GitHub Actions
  workflow_dispatch:

# Гарантирует, что только один экземпляр воркфлоу выполняется одновременно
concurrency:
  group: kinopoisk-data-sync
  cancel-in-progress: false

jobs:
  # ЗАДАЧА №1: СБОРЩИК (выполняется каждый час)
  collector:
    name: "Run Collector"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests huggingface_hub

      - name: Run collector script
        env:
          KINOPOISK_API_KEYS: ${{ secrets.KINOPOISK_API_KEYS }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MAX_REQUESTS_PER_RUN: '200'
        run: python collector.py

  # ЗАДАЧА №2: КОНСОЛИДАТОР (выполняется в 03:00 UTC ежедневно)
  consolidator:
    name: "Run Consolidator"
    # ИСПРАВЛЕНО: правильное условие для запуска в 3 утра UTC
    if: (github.event.schedule == '0 3 * * *') || (github.event_name == 'workflow_dispatch')
    needs: collector
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests huggingface_hub

      - name: Run consolidator script
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python consolidator.py
