# Имя воркфлоу
name: Data Pipeline

on:
  # Запуск по расписанию в начале каждого часа
  schedule:
    - cron: '0 * * * *'
  # Позволяет запускать вручную из интерфейса GitHub Actions
  workflow_dispatch:

# Гарантирует, что только один экземпляр этого воркфлоу (collector или consolidator)
# может работать в любой момент времени.
concurrency:
  group: kinopoisk-data-sync
  cancel-in-progress: false

jobs:
  # ЗАДАЧА №1: СБОРЩИК (ЛЕГКИЙ, ЧАСТЫЙ)
  collector:
    name: "Run Collector"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests huggingface_hub

      - name: Run collector script
        env:
          # ВАЖНО: В настройках репозитория создайте секрет 'KINOPOISK_API_KEYS'
          # и запишите туда все ваши ключи через запятую, без пробелов.
          # Пример: "key1,key2,key3,key4"
          KINOPOISK_API_KEYS: ${{ secrets.KINOPOISK_API_KEYS }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          MAX_REQUESTS_PER_RUN: '100'
        run: python collector.py

  # ЗАДАЧА №2: КОНСОЛИДАТОР (ТЯЖЕЛЫЙ, РЕДКИЙ)
  consolidator:
    name: "Run Consolidator"
    # Эта задача начнется только после того, как задача 'collector' успешно завершится.
    needs: collector
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether to run
        id: decision
        # Логика запуска:
        # Условие: текущий час 03:00 по UTC ИЛИ воркфлоу запущен вручную.
        run: |
          if [ "$(date -u +'%H')" == "03" ] || [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "SHOULD_RUN=true" >> $GITHUB_OUTPUT
            echo "Consolidator will run."
          else
            echo "SHOULD_RUN=false" >> $GITHUB_OUTPUT
            echo "It is not 3 AM UTC. Skipping consolidator."
          fi

      - name: Checkout repository code
        if: steps.decision.outputs.SHOULD_RUN == 'true'
        uses: actions/checkout@v4

      - name: Set up Python
        if: steps.decision.outputs.SHOULD_RUN == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: steps.decision.outputs.SHOULD_RUN == 'true'
        run: pip install requests huggingface_hub

      - name: Run consolidator script
        if: steps.decision.outputs.SHOULD_RUN == 'true'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python consolidator.py


